bind 127.0.0.1
protected-mode yes
port 6379
timeout 0
tcp-keepalive 300

dbfilename dump.rdb

appendonly yes
appendfilename "appendonly-local.aof"
appendfsync everysec

save 900 1
save 300 10
save 60 10000

loglevel notice

lazyfree-lazy-eviction yes
lazyfree-lazy-expire yes
